[project]
name = "fullproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "anakom978", email = "anakom.suvonvorn@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
fullproject = "fullproject:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
