"""Generate the diagrams that can be derived from source, so they cannot drift.

    uv run python scripts/gen_diagrams.py

Every diagram this script emits is built by *reading the running system* — the transition
table, the loaded domain pack, the pydantic models, the event registry, the adapter
packages on disk. None of it is transcribed by hand, which is the point: a diagram that is
retyped from memory is a comment, and comments rot. These are closer to tests.

Hand-drawn diagrams (architecture, sequence flows, roadmaps) live beside the generated ones
in `docs/diagrams/src/` and are marked `handwritten` in the header of each file.

After running this, render to SVG with `scripts/render_diagrams.mjs`.
"""

from __future__ import annotations

import itertools
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from readycall.console import enable_utf8  # noqa: E402
from readycall.domain import events as ev  # noqa: E402
from readycall.domain.enums import (  # noqa: E402
    TERMINAL_STATES,
    AgentIntent,
    AgentSystemState,
    AssuranceLevel,
    CallState,
    DegradationReason,
    ProductLine,
)
from readycall.domainpack import DomainPack  # noqa: E402
from readycall.services.call_orchestrator import machine  # noqa: E402
from readycall.voiceprompts import PromptPack, PromptRole  # noqa: E402

OUT = ROOT / "docs" / "diagrams" / "src"

BANNER = (
    "%% GENERATED by scripts/gen_diagrams.py - do not edit by hand.\n%% Source of truth: {src}\n"
)


def write(name: str, body: str, *, src: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{name}.mmd").write_text(BANNER.format(src=src) + body.strip() + "\n", encoding="utf-8")
    print(f"  wrote {name}.mmd")


def q(text: str) -> str:
    """Quote a mermaid label so punctuation and Thai text survive."""
    return '"' + text.replace('"', "'") + '"'


def lbl(*parts: str) -> str:
    """Quote a multi-LINE mermaid label. Mermaid takes a literal newline in a label."""
    return q("\n".join(parts))


# --------------------------------------------------------------------------------------
# 1. The call state machine, straight off the transition table.
# --------------------------------------------------------------------------------------


def state_machine() -> None:
    lines = ["stateDiagram-v2", "    direction TB"]
    for start in sorted(machine.START_STATES, key=lambda s: s.value):
        lines.append(f"    [*] --> {start.name}")
    for state in CallState:
        for target in sorted(machine.TRANSITIONS[state], key=lambda s: s.value):
            arrow = f"    {state.name} --> {target.name}"
            if state is target:
                arrow += " : re-match"
            lines.append(arrow)
    for state in sorted(TERMINAL_STATES, key=lambda s: s.value):
        lines.append(f"    {state.name} --> [*]")
    lines.append("")
    for state in CallState:
        note = _STATE_NOTES.get(state)
        if note:
            lines.append(f"    note right of {state.name}")
            lines.append(f"        {note}")
            lines.append("    end note")
    write(
        "state_machine",
        "\n".join(lines),
        src="readycall.services.call_orchestrator.machine.TRANSITIONS",
    )


#: `ABANDONED` and `FAILED` are reachable from almost every state, so drawing them turns
#: the full diagram into a hairball that hides the actual flow. The readable view omits
#: them and says so; `state_machine.mmd` remains the complete, unfiltered truth.
_NOISY_STATES: frozenset[CallState] = frozenset({CallState.ABANDONED, CallState.FAILED})


def state_machine_readable() -> None:
    """The same table minus the two ubiquitous escape hatches, for humans."""
    lines = ["stateDiagram-v2", "    direction TB"]
    for start in sorted(machine.START_STATES, key=lambda s: s.value):
        lines.append(f"    [*] --> {start.name}")
    for state in CallState:
        if state in _NOISY_STATES:
            continue
        for target in sorted(machine.TRANSITIONS[state], key=lambda s: s.value):
            if target in _NOISY_STATES:
                continue
            arrow = f"    {state.name} --> {target.name}"
            if state is target:
                arrow += " : re-match (RONA)"
            lines.append(arrow)
    for state in sorted(TERMINAL_STATES - _NOISY_STATES, key=lambda s: s.value):
        lines.append(f"    {state.name} --> [*]")
    omitted = ", ".join(sorted(s.name for s in _NOISY_STATES))
    lines += [
        "",
        "    note left of QUEUED",
        f"        {omitted} are omitted here.",
        "        Nearly every state can reach them,",
        "        and drawing that hides the real flow.",
        "        See state_machine.svg for the full table.",
        "    end note",
        "",
        "    note right of INTAKE_ACTIVE",
        "        QUEUED and INTAKE_ACTIVE can BOTH",
        "        jump straight to MATCHED: leaving the",
        "        queue depends on an agent being free,",
        "        never on intake having finished (D12).",
        "    end note",
        "",
        "    note right of OFFERED",
        "        OFFERED --> MATCHED is RONA: a declined",
        "        or timed-out offer re-matches someone",
        "        else instead of stranding the caller (D33).",
        "    end note",
    ]
    write(
        "state_machine_readable",
        "\n".join(lines),
        src="the same TRANSITIONS table, minus ABANDONED and FAILED",
    )


_STATE_NOTES: dict[CallState, str] = {
    CallState.INTENT_CREATED: "app path only (D19)",
    CallState.OFFERED: "offer card rings in the BROWSER (D32)",
    CallState.INTAKE_ACTIVE: "may jump straight to MATCHED (D12/D21)",
}


# --------------------------------------------------------------------------------------
# 2. The keypad menu tree, straight off menus.yaml.
# --------------------------------------------------------------------------------------


def menu_tree(pack: DomainPack) -> None:
    lines = ["flowchart LR", "    caller([caller dials]):::entry"]
    root = pack.menus.get("product_line")
    if root is None:
        return
    lines.append(f"    caller --> product_line[{q('STEP 1  which product line?')}]")
    for option in root.options:
        target = option.next_menu or "unknown"
        lines.append(
            f"    product_line -- {q(option.key + '  ' + option.label_th)} --> {target}"
            f"[{q('STEP 2  ' + target.replace('_', ' '))}]"
        )
    for menu_id, menu in pack.menus.items():
        if menu_id == "product_line":
            continue
        for option in menu.options:
            if not option.intent:
                continue
            spec = pack.intents.get(option.intent)
            queue = pack.queue_for_intent(option.intent) if spec else "?"
            node = option.intent.replace(".", "_")
            lines.append(
                f"    {menu_id} -- {q(option.key + '  ' + option.label_th)} --> "
                f"{node}[{q(option.intent + chr(10) + '-> ' + queue)}]:::intent"
            )
    lines.append("    classDef entry fill:#1f6feb,stroke:#0b3d91,color:#fff")
    lines.append("    classDef intent fill:#eef4ff,stroke:#5b8def,color:#0b2545")
    write("menu_tree", "\n".join(lines), src="config/menus.yaml + config/intents.yaml")


# --------------------------------------------------------------------------------------
# 3. The routing chain: intent -> skill -> queue, straight off the pack.
# --------------------------------------------------------------------------------------


def routing_chain(pack: DomainPack) -> None:
    lines = ["flowchart LR"]
    seen_skills: set[str] = set()
    seen_queues: set[str] = set()
    for code, spec in sorted(pack.intents.items()):
        intent_node = "i_" + code.replace(".", "_")
        skill_node = "s_" + spec.skill
        label = f"{code}\n{spec.label_th}"
        lines.append(f"    {intent_node}[{q(label)}]:::intent --> {skill_node}")
        if spec.skill not in seen_skills:
            seen_skills.add(spec.skill)
            skill = pack.skills.get(spec.skill)
            if skill:
                lines.append(f"    {skill_node}([{q(spec.skill)}]):::skill --> q_{skill.queue}")
                if skill.queue not in seen_queues:
                    seen_queues.add(skill.queue)
                    queue = pack.queues.get(skill.queue)
                    sla = f"\nSLA {queue.sla_seconds}s" if queue else ""
                    lines.append(f"    q_{skill.queue}[{q(skill.queue + sla)}]:::queue")
    for queue_id, queue in sorted(pack.queues.items()):
        if queue.overflow_queue:
            lines.append(f"    q_{queue_id} -. {q('overflow')} .-> q_{queue.overflow_queue}")
    lines.append("    classDef intent fill:#eef4ff,stroke:#5b8def,color:#0b2545")
    lines.append("    classDef skill fill:#fff4e6,stroke:#e8a33d,color:#4a2f00")
    lines.append("    classDef queue fill:#e9f7ef,stroke:#2f9e5f,color:#08361d")
    write("routing_chain", "\n".join(lines), src="config/intents.yaml + config/skills.yaml")


# --------------------------------------------------------------------------------------
# 4. Published numbers and what each implies.
# --------------------------------------------------------------------------------------


def dids(pack: DomainPack) -> None:
    lines = ["flowchart LR"]
    for number, spec in sorted(pack.dids.items()):
        node = "d_" + number.replace("+", "p")
        skip = "skips step 1" if spec.skip_product_menu else "MENU ASKS step 1"
        extra = f"\nurgency floor: {spec.urgency_floor}" if spec.urgency_floor else ""
        lines.append(
            f"    {node}[{q(number + chr(10) + spec.label.split(' - ')[0])}]:::did"
            f" --> r_{node}[{q('line: ' + str(spec.product_line) + chr(10) + skip + extra)}]"
            f" --> {spec.default_queue}[{q('default: ' + spec.default_queue)}]:::queue"
        )
    lines.append("    classDef did fill:#eef4ff,stroke:#5b8def,color:#0b2545")
    lines.append("    classDef queue fill:#e9f7ef,stroke:#2f9e5f,color:#08361d")
    write("dids", "\n".join(lines), src="config/dids.yaml")


# --------------------------------------------------------------------------------------
# 5. The event catalogue, from the registry.
# --------------------------------------------------------------------------------------


def event_catalogue() -> None:
    groups: dict[str, list[str]] = {}
    for event_type in ev.EVENT_TYPES:
        prefix = event_type.name.split(".")[0]
        groups.setdefault(prefix, []).append(event_type.name)
    lines = ["flowchart TB"]
    for prefix, names in sorted(groups.items()):
        lines.append(f"    subgraph {prefix}[{q(prefix + '.*')}]")
        lines.append("        direction TB")
        for name in sorted(names):
            lines.append(f"        {name.replace('.', '_')}[{q(name)}]")
        lines.append("    end")
    write("events", "\n".join(lines), src="readycall.domain.events.EVENT_TYPES")


# --------------------------------------------------------------------------------------
# 6. Ports and their adapters, from the packages on disk.
# --------------------------------------------------------------------------------------


def ports_adapters() -> None:
    ports_dir = ROOT / "src" / "readycall" / "ports"
    adapters_dir = ROOT / "src" / "readycall" / "adapters"
    lines = ["flowchart LR", '    subgraph core["services/ + domain/ (no vendor imports)"]']
    lines.append("        logic([business logic]):::core")
    lines.append("    end")
    for port_file in sorted(ports_dir.glob("*.py")):
        if port_file.stem == "__init__":
            continue
        port = port_file.stem
        lines.append(f"    logic --> P_{port}[{q('ports/' + port + '.py')}]:::port")
        pkg = adapters_dir / port
        impls = sorted(p.stem for p in pkg.glob("*.py") if p.stem != "__init__")
        if not impls:
            lines.append(f"    P_{port} -.-> A_{port}_none[{q('no adapter yet')}]:::todo")
        for impl in impls:
            lines.append(f"    P_{port} --> A_{port}_{impl}[{q(impl + '.py')}]:::adapter")
    lines.append("    classDef core fill:#1f6feb,stroke:#0b3d91,color:#fff")
    lines.append("    classDef port fill:#fff4e6,stroke:#e8a33d,color:#4a2f00")
    lines.append("    classDef adapter fill:#e9f7ef,stroke:#2f9e5f,color:#08361d")
    lines.append("    classDef todo fill:#f5f5f5,stroke:#bbb,color:#666,stroke-dasharray:4 3")
    write("ports_adapters", "\n".join(lines), src="src/readycall/ports/ + adapters/ on disk")


# --------------------------------------------------------------------------------------
# 7. The assurance ladder, from the enum plus the resolver's rules.
# --------------------------------------------------------------------------------------


def assurance_ladder() -> None:
    rungs = [
        (AssuranceLevel.L0_ANONYMOUS, "nothing matched", "no name, no policy, no figures"),
        (AssuranceLevel.L1_PROBABLE, "caller ID matched a customer", "name only - NO policy no."),
        (AssuranceLevel.L2_STRONG, "caller ID + pending app intent", "policy details unlocked"),
        (AssuranceLevel.L3_VERIFIED, "app token, or verified challenge", "everything"),
    ]
    lines = ["flowchart TB"]
    for level, reached, shows in rungs:
        node = level.name
        head = f"{level}  (rank {level.rank})"
        lines.append(f"    {node}[{lbl(head, reached, 'shows: ' + shows)}]:::r{level.rank}")
    lines.append("    L0_ANONYMOUS -- verified challenge --> L3_VERIFIED")
    lines.append("    L1_PROBABLE -- agent confirms / typed policy no. matches --> L3_VERIFIED")
    lines.append("    L2_STRONG -- agent confirms --> L3_VERIFIED")
    lines.append("    L1_PROBABLE -- 'not this person' --> L0_ANONYMOUS")
    lines.append("    L2_STRONG -- 'not this person' --> L0_ANONYMOUS")
    lines.append(f"    DISCLOSE{{{q('may_disclose_policy_details')}}}:::gate")
    lines.append("    L2_STRONG --> DISCLOSE")
    lines.append("    L3_VERIFIED --> DISCLOSE")
    lines.append("    classDef r0 fill:#fdecea,stroke:#d93025,color:#5c1a13")
    lines.append("    classDef r1 fill:#fff4e6,stroke:#e8a33d,color:#4a2f00")
    lines.append("    classDef r2 fill:#eef4ff,stroke:#5b8def,color:#0b2545")
    lines.append("    classDef r3 fill:#e9f7ef,stroke:#2f9e5f,color:#08361d")
    lines.append("    classDef gate fill:#1f6feb,stroke:#0b3d91,color:#fff")
    write(
        "assurance_ladder",
        "\n".join(lines),
        src="readycall.domain.enums.AssuranceLevel + services/identity/resolver.py + D42",
    )


# --------------------------------------------------------------------------------------
# 8. Agent state: the platform's axis and the person's axis (D33).
# --------------------------------------------------------------------------------------


def agent_state() -> None:
    lines = ["flowchart TB", '    subgraph sys["system_state - set by the PLATFORM"]']
    lines.append("        direction LR")
    order = [
        AgentSystemState.OFFLINE,
        AgentSystemState.AVAILABLE,
        AgentSystemState.OFFERING,
        AgentSystemState.ON_CALL,
        AgentSystemState.AFTER_CALL_WORK,
    ]
    for a, b in itertools.pairwise(order):
        lines.append(f"        {a.name} --> {b.name}")
    acw, available = AgentSystemState.AFTER_CALL_WORK.name, AgentSystemState.AVAILABLE.name
    # D45: saving the wrap-up form closes the call record; it does NOT make the agent
    # offerable. Only the person clicking Ready ends ACW, because the rest of their
    # post-call work happens in systems we do not own.
    lines.append(f"        {acw} -- {q('the PERSON clicks Ready (D45)')} --> {available}")
    offering = AgentSystemState.OFFERING.name
    lines.append(f"        {offering} -- declined / RONA --> {available}")
    lines.append("    end")
    lines.append('    subgraph person["agent_intent - set by the PERSON"]')
    lines.append("        direction LR")
    for intent in AgentIntent:
        lines.append(f"        I_{intent.name}[{q(str(intent))}]")
    lines.append("    end")
    eligible = q("offerable = AVAILABLE and intent in (ready, last_call)")
    lines.append(f"    sys -.-> ELIGIBLE{{{eligible}}}:::gate")
    lines.append("    person -.-> ELIGIBLE")
    why = lbl(
        "Why two axes? Because 'the platform has no work for you'",
        "and 'I am ready for another caller' are different facts.",
        "Conflating them is how a form submission ends up asserting",
        "an availability nobody confirmed - and the next caller",
        "rings an empty desk for a full offer timeout. (D45)",
    )
    lines.append(f"    NOTE[{why}]:::note")
    lines.append("    classDef gate fill:#1f6feb,stroke:#0b3d91,color:#fff")
    lines.append("    classDef note fill:#fffbe6,stroke:#d4a72c,color:#4a3800")
    write(
        "agent_state",
        "\n".join(lines),
        src="readycall.domain.enums.AgentSystemState + AgentIntent (D33, D45)",
    )


# --------------------------------------------------------------------------------------
# 9. Degradation reasons, from the enum.
# --------------------------------------------------------------------------------------


def degradation() -> None:
    causes = {
        DegradationReason.NO_CONSENT: "caller declined recording",
        DegradationReason.INTAKE_DECLINED: "caller pressed 2",
        DegradationReason.STT_UNAVAILABLE: "speech worker down",
        DegradationReason.LLM_UNAVAILABLE: "model down or too slow",
        DegradationReason.CORE_DATA_UNAVAILABLE: "bank core unreachable",
        DegradationReason.CORE_DATA_STALE: "served from cache",
        DegradationReason.LOW_ASSURANCE: "identity not strong enough",
        DegradationReason.MEDIA_FORK_FAILED: "no audio to transcribe",
        DegradationReason.TIMED_OUT: "stage exceeded its budget",
    }
    lines = [
        "flowchart LR",
        f"    FULL[{lbl('FULL BRIEF', 'context + speech + AI')}]:::ok",
    ]
    ctx = lbl("CONTEXT-ONLY BRIEF", "data + keypad menu", "BUILT AT P1 - never fails")
    lines.append(f"    CTX[{ctx}]:::warn")
    lines.append(f"    MIN[{lbl('MINIMAL', 'queue + what they pressed')}]:::bad")
    lines.append(f"    CALL[{lbl('THE CALL CONNECTS ANYWAY', '(D12)')}]:::always")
    for reason, why in causes.items():
        node = "R_" + reason.name
        lines.append(f"    FULL -- {lbl(str(reason), why)} --> {node}[ ]:::dot")
        target = "MIN" if reason in {DegradationReason.CORE_DATA_UNAVAILABLE} else "CTX"
        lines.append(f"    {node} --> {target}")
    lines.append("    CTX --> CALL")
    lines.append("    MIN --> CALL")
    lines.append("    classDef ok fill:#e9f7ef,stroke:#2f9e5f,color:#08361d")
    lines.append("    classDef warn fill:#fff4e6,stroke:#e8a33d,color:#4a2f00")
    lines.append("    classDef bad fill:#fdecea,stroke:#d93025,color:#5c1a13")
    lines.append("    classDef always fill:#1f6feb,stroke:#0b3d91,color:#fff")
    lines.append("    classDef dot fill:#fff,stroke:#ccc,color:#666")
    write("degradation_ladder", "\n".join(lines), src="readycall.domain.enums.DegradationReason")


# --------------------------------------------------------------------------------------
# 10. The domain model, as a class diagram, from the pydantic models.
# --------------------------------------------------------------------------------------

_MODEL_GROUPS: dict[str, tuple[str, ...]] = {
    "BANK_DATA_read_only_D5": (
        "Customer",
        "Policy",
        "Coverage",
        "Claim",
        "Product",
        "Interaction",
        "Holding",
        "LifeEvent",
    ),
    "CONTEXT_we_assemble": ("Customer360", "ContextSnapshot", "FieldProvenance"),
    "THE_CALL": ("CallSession", "CallIntent", "Consent", "StateTransition", "QueueEntry"),
    "SPEECH": ("TranscriptTurn", "IntakeResult", "ExtractedEntity"),
    "WHAT_THE_AGENT_READS": (
        "CaseBrief",
        "IntentPrediction",
        "RecommendedAction",
        "ConfidenceBreakdown",
        "IdentityResolution",
    ),
    "AGENTS_AND_MATCHING": (
        "Agent",
        "AgentSkill",
        "AgentLanguage",
        "AgentPresence",
        "MatchingDecision",
        "MatchCandidate",
        "FitBreakdown",
        "UrgencyBreakdown",
        "Assignment",
    ),
}

_RELATIONS: tuple[tuple[str, str, str], ...] = (
    ("Customer", "Policy", "holds"),
    ("Policy", "Coverage", "typed figures (D16)"),
    ("Policy", "Claim", "against"),
    ("Customer", "Interaction", "history"),
    ("Customer", "Holding", "bank products"),
    ("Customer", "LifeEvent", "signals"),
    ("Customer360", "Customer", "wraps"),
    ("Customer360", "Policy", "active + relevant"),
    ("ContextSnapshot", "Customer360", "freezes"),
    ("ContextSnapshot", "FieldProvenance", "says who told us"),
    ("CallSession", "Consent", "scopes (D14)"),
    ("CallSession", "StateTransition", "full log"),
    ("CallSession", "IdentityResolution", "who + how sure"),
    ("CallIntent", "CallSession", "app path only"),
    ("IntakeResult", "TranscriptTurn", "turns"),
    ("IntakeResult", "ExtractedEntity", "slots"),
    ("CaseBrief", "ContextSnapshot", "what we knew"),
    ("CaseBrief", "IntentPrediction", "why they called"),
    ("CaseBrief", "RecommendedAction", "what to do"),
    ("CaseBrief", "IdentityResolution", "gates disclosure"),
    ("Agent", "AgentSkill", "can handle"),
    ("Agent", "AgentLanguage", "CEFR (D38)"),
    ("Agent", "AgentPresence", "live state"),
    ("MatchingDecision", "MatchCandidate", "every option scored"),
    ("MatchCandidate", "FitBreakdown", "explainable"),
    ("MatchingDecision", "Assignment", "the offer (D33)"),
)


def domain_models() -> None:
    import readycall.domain.models as m

    lines = ["classDiagram", "    direction TB"]
    for group, names in _MODEL_GROUPS.items():
        lines.append(f"    namespace {group} {{")
        for name in names:
            model = getattr(m, name, None)
            if model is None:
                raise SystemExit(f"model {name} named in _MODEL_GROUPS does not exist")
            lines.append(f"        class {name}")
        lines.append("    }")
    for name in (n for names in _MODEL_GROUPS.values() for n in names):
        model = getattr(m, name)
        fields = list(getattr(model, "model_fields", {}))
        shown = fields[:6]
        for f in shown:
            lines.append(f"    {name} : {f}")
        if len(fields) > len(shown):
            lines.append(f"    {name} : ...{len(fields) - len(shown)} more")
    for left, right, label in _RELATIONS:
        lines.append(f"    {left} --> {right} : {label}")
    write("domain_models", "\n".join(lines), src="readycall.domain.models (pydantic fields)")


# --------------------------------------------------------------------------------------
# 11. Product lines, so the "insurance is not just health" point is visible.
# --------------------------------------------------------------------------------------


def product_lines(pack: DomainPack) -> None:
    lines = ["flowchart TB", f"    ROOT[{q('ProductLine')}]:::root"]
    for line in ProductLine:
        intents = [c for c, s in pack.intents.items() if s.line is line]
        label = f"{line}\n{len(intents)} intents"
        lines.append(f"    ROOT --> L_{line.name}[{q(label)}]:::line")
        for code in sorted(intents):
            spec = pack.intents[code]
            mark = " *catch-all*" if spec.is_catch_all else ""
            lines.append(f"    L_{line.name} --> i_{code.replace('.', '_')}[{q(code + mark)}]")
    lines.append("    classDef root fill:#1f6feb,stroke:#0b3d91,color:#fff")
    lines.append("    classDef line fill:#eef4ff,stroke:#5b8def,color:#0b2545")
    write("product_lines", "\n".join(lines), src="ProductLine enum + config/intents.yaml")


#: Tables grouped by what they are *for*, so the picture reads as a system rather than an
#: alphabetical list. A table missing from here still appears, under "other" — the grouping
#: is presentation, and the generator must never silently drop a real table.
_TABLE_GROUPS: dict[str, tuple[str, ...]] = {
    "the call": ("call_sessions", "call_state_transitions", "context_snapshots"),
    "the agent side": ("agent_state_log", "assignments", "call_wrapups"),
    "the record (PDPA)": ("identity_attestations", "keypad_captures"),
    "explainability": ("matching_decisions",),
}

#: What is deliberately NOT a table (`D78`), and what each is computed from. Hand-kept,
#: because an absence cannot be read off `Base.metadata` — but every source named here is
#: checked against the real metadata below, so a rename cannot leave it lying.
_DERIVED: tuple[tuple[str, str, str], ...] = (
    ("current presence", "agent_state_log", "newest row per agent (D76)"),
    ("the waiting pool", "call_sessions", "state in queued/matched (D78)"),
    ("live identity", "call_sessions", "the identity column (D78)"),
    ("accrued wait", "call_sessions", "recomputed from queued_at (D22)"),
)


def db_schema() -> None:
    """Every table we write, read straight off the SQLAlchemy metadata.

    Generated rather than drawn because the whole claim of `D78` is *this* set and no more:
    a table that appears here without a reason, or a derived thing that quietly becomes a
    table, is exactly the drift the picture exists to prevent.
    """
    import readycall.db.models  # noqa: F401  (registers every table on the metadata)
    from readycall.db.base import Base

    tables = {name.split(".")[-1]: table for name, table in Base.metadata.tables.items()}
    grouped = {t for names in _TABLE_GROUPS.values() for t in names}
    ungrouped = tuple(sorted(set(tables) - grouped))
    groups = dict(_TABLE_GROUPS)
    if ungrouped:
        groups["other"] = ungrouped

    lines = ["flowchart TB"]
    # Enumerated, not hashed: `hash()` on a string is randomised per process, so a hashed
    # id would make this file differ between runs and `test_diagrams.py` would fail at
    # random. A generated diagram has to be byte-stable or the freshness check is noise.
    for n, (group, names) in enumerate(groups.items()):
        lines.append(f"    subgraph g_{n}[{q(group)}]")
        lines.append("        direction TB")
        for name in names:
            table = tables.get(name)
            if table is None:
                continue
            keys = [c.name for c in table.columns if c.primary_key]
            indexed = sorted({c.name for ix in table.indexes for c in ix.columns})
            jsonish = [
                c.name for c in table.columns if type(c.type).__name__ in {"Json", "JSON", "JSONB"}
            ]
            body = [f"<b>{name}</b>", "pk: " + ", ".join(keys)]
            if indexed:
                body.append("indexed: " + ", ".join(indexed))
            if jsonish:
                body.append("json: " + ", ".join(jsonish))
            body.append(f"{len(table.columns)} columns")
            lines.append(f"        t_{name}[{lbl(*body)}]:::tbl")
        lines.append("    end")

    for name, table in sorted(tables.items()):
        for fk in table.foreign_keys:
            target = fk.column.table.name
            if target != name:
                lines.append(f"    t_{name} -. {q('FK')} .-> t_{target}")

    lines.append(f"    D[{lbl('NOT tables, on purpose (D78)', '')}]:::hdr")
    for label, source, how in _DERIVED:
        assert source in tables, f"{source} is not a real table; _DERIVED is stale"
        node = "d_" + label.replace(" ", "_")
        lines.append(f"    D --- {node}[{lbl(label, how)}]:::derived")
        lines.append(f"    t_{source} == {q('derived from')} ==> {node}")

    lines.append("    classDef tbl fill:#e9f7ef,stroke:#2f9e5f,color:#08361d")
    lines.append("    classDef derived fill:#fffbe6,stroke:#d4a72c,color:#4a3800")
    lines.append("    classDef hdr fill:#fff,stroke:#d4a72c,color:#4a3800,stroke-dasharray:4 3")
    write("db_schema", chr(10).join(lines), src="readycall.db.models via Base.metadata")


def voice_prompts(pack: DomainPack, prompts: PromptPack) -> None:
    """Who asks for which line — read off the pack and the flow table.

    The point of drawing this is the arrows, not the boxes: a prompt id is a string in
    one file and a definition in another, and this is the only place the join is visible.
    An orphan shows up as a box nothing points at.
    """
    lines = ["flowchart LR"]
    referenced = prompts.referenced_ids(pack)

    lines.append('    subgraph flow["services/ivr asks by ROLE"]')
    for role in PromptRole:
        lines.append(f"        role_{role.value}[{q(role.value)}]:::role")
    lines.append("    end")

    lines.append('    subgraph cfg["menus.yaml + dids.yaml name an ID"]')
    for menu_id in sorted(pack.menus):
        lines.append(f"        menu_{menu_id}[{q(menu_id)}]:::cfg")
    for number in sorted(pack.dids):
        lines.append(f"        did_{number.replace('+', 'p')}[{q(number)}]:::cfg")
    lines.append("    end")

    def node(prompt_id: str) -> str:
        return "p_" + prompt_id.replace(".", "_")

    for prompt_id in sorted(prompts.prompts):
        spec = prompts.prompts[prompt_id]
        style = "dyn" if spec.is_dynamic else "static"
        suffix = f"{chr(10)}{{{', '.join(spec.slots)}}}" if spec.slots else ""
        lines.append(f"    {node(prompt_id)}[{q(prompt_id + suffix)}]:::{style}")

    for role, prompt_id in sorted(prompts.flow.items()):
        lines.append(f"    role_{role.value} --> {node(prompt_id)}")
    for menu_id, menu in sorted(pack.menus.items()):
        lines.append(f"    menu_{menu_id} --> {node(menu.prompt)}")
    for number, did in sorted(pack.dids.items()):
        lines.append(f"    did_{number.replace('+', 'p')} --> {node(did.greeting_prompt)}")

    orphans = sorted(set(prompts.prompts) - referenced)
    for prompt_id in orphans:
        lines.append(f"    class {node(prompt_id)} orphan")

    lines.append("    classDef role fill:#eef4ff,stroke:#5b8def,color:#0b2545")
    lines.append("    classDef cfg fill:#fff4e6,stroke:#e8a33d,color:#4a2f00")
    lines.append("    classDef static fill:#e9f7ef,stroke:#2f9e5f,color:#08361d")
    lines.append("    classDef dyn fill:#f3e8ff,stroke:#8b5cf6,color:#2e1065")
    lines.append("    classDef orphan fill:#ffe4e6,stroke:#e11d48,color:#4c0519")
    write(
        "voice_prompts",
        "\n".join(lines),
        src="config/voice_prompts.yaml + config/menus.yaml + config/dids.yaml",
    )


def main() -> int:
    enable_utf8()
    pack = DomainPack.load(ROOT / "config")
    prompts = PromptPack.load(ROOT / "config" / "voice_prompts.yaml")
    print("generating derived diagrams:")
    state_machine()
    state_machine_readable()
    menu_tree(pack)
    routing_chain(pack)
    dids(pack)
    event_catalogue()
    ports_adapters()
    assurance_ladder()
    agent_state()
    degradation()
    domain_models()
    product_lines(pack)
    db_schema()
    voice_prompts(pack, prompts)
    where = OUT.relative_to(ROOT) if OUT.is_relative_to(ROOT) else OUT
    print()
    print(f"{len(list(OUT.glob('*.mmd')))} .mmd files in {where}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
