"""transcript_turns

Revision ID: 3ef5ad5d89f6
Revises: 7bb7b6ffe6ba
Create Date: 2026-09-06 05:45:38.186393

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types are emitted by autogenerate as fully-qualified names, so the module
# has to be importable from inside the migration. Without this every generated file dies
# with `NameError: name 'readycall' is not defined` on the first Utc or Json column.


# revision identifiers, used by Alembic.
revision: str = "3ef5ad5d89f6"
down_revision: str | Sequence[str] | None = "7bb7b6ffe6ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcript_turns",
        sa.Column("turn_id", sa.String(length=40), nullable=False),
        sa.Column("call_session_id", sa.String(length=40), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("speaker_role", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("t_start_ms", sa.Integer(), nullable=False),
        sa.Column("t_end_ms", sa.Integer(), nullable=False),
        sa.Column("asr_confidence", sa.Float(), nullable=True),
        sa.Column("engine", sa.String(length=64), nullable=True),
        sa.Column("engine_version", sa.String(length=64), nullable=True),
        sa.Column("is_final", sa.Boolean(), nullable=False),
        sa.Column("intake_id", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_session_id"],
            ["readycall.call_sessions.call_session_id"],
            name=op.f("fk_transcript_turns_call_session_id_call_sessions"),
        ),
        sa.PrimaryKeyConstraint("turn_id", name=op.f("pk_transcript_turns")),
        schema="readycall",
    )
    op.create_index(
        "ix_transcript_turns_call_seq",
        "transcript_turns",
        ["call_session_id", "seq"],
        unique=False,
        schema="readycall",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transcript_turns_call_seq", table_name="transcript_turns", schema="readycall")
    op.drop_table("transcript_turns", schema="readycall")
    # ### end Alembic commands ###
