"""call sessions, transitions, agent state log

Revision ID: 6991a6b2b212
Revises:
Create Date: 2026-08-25 15:47:04.013617

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import readycall.db.base

# revision identifiers, used by Alembic.
revision: str = "6991a6b2b212"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call_sessions",
        sa.Column("call_session_id", sa.String(length=40), nullable=False),
        sa.Column("entry_channel", sa.String(length=24), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("created_at", readycall.db.base.Utc(timezone=True), nullable=False),
        sa.Column("trace_id", sa.String(length=40), nullable=True),
        sa.Column("intent_id", sa.String(length=40), nullable=True),
        sa.Column("customer_id", sa.String(length=32), nullable=True),
        sa.Column("caller_number", sa.String(length=32), nullable=True),
        sa.Column("dialled_did", sa.String(length=32), nullable=True),
        sa.Column("product_line", sa.String(length=16), nullable=False),
        sa.Column("product_code", sa.String(length=64), nullable=True),
        sa.Column("telephony_call_id", sa.String(length=64), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("preferred_language", sa.String(length=8), nullable=False),
        sa.Column("acceptable_languages", readycall.db.base.Json(), nullable=False),
        sa.Column("menu_path", readycall.db.base.Json(), nullable=False),
        sa.Column("menu_intent_code", sa.String(length=64), nullable=True),
        sa.Column("queue_id", sa.String(length=32), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("queued_at", readycall.db.base.Utc(timezone=True), nullable=True),
        sa.Column("answered_at", readycall.db.base.Utc(timezone=True), nullable=True),
        sa.Column("ended_at", readycall.db.base.Utc(timezone=True), nullable=True),
        sa.Column("end_reason", sa.String(length=64), nullable=True),
        sa.Column("snapshot_id", sa.String(length=40), nullable=True),
        sa.Column("intake_id", sa.String(length=40), nullable=True),
        sa.Column("brief_version", sa.Integer(), nullable=False),
        sa.Column("assigned_agent_id", sa.String(length=32), nullable=True),
        sa.Column("identity", readycall.db.base.Json(), nullable=True),
        sa.Column("consents", readycall.db.base.Json(), nullable=False),
        sa.Column("stage_timings_ms", readycall.db.base.Json(), nullable=False),
        sa.PrimaryKeyConstraint("call_session_id", name=op.f("pk_call_sessions")),
        schema="readycall",
    )
    op.create_index(
        "ix_call_sessions_customer_id",
        "call_sessions",
        ["customer_id"],
        unique=False,
        schema="readycall",
    )
    op.create_index(
        "ix_call_sessions_queued_at",
        "call_sessions",
        ["queued_at"],
        unique=False,
        schema="readycall",
    )
    op.create_index(
        "ix_call_sessions_state", "call_sessions", ["state"], unique=False, schema="readycall"
    )
    op.create_index(
        "ix_call_sessions_telephony_call_id",
        "call_sessions",
        ["telephony_call_id"],
        unique=False,
        schema="readycall",
    )
    op.create_table(
        "agent_state_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("at", readycall.db.base.Utc(timezone=True), nullable=False),
        sa.Column("system_state", sa.String(length=32), nullable=False),
        sa.Column("agent_intent", sa.String(length=32), nullable=False),
        sa.Column("set_by", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("call_session_id", sa.String(length=40), nullable=True),
        sa.Column("acw_seconds", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_session_id"],
            ["readycall.call_sessions.call_session_id"],
            name=op.f("fk_agent_state_log_call_session_id_call_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_state_log")),
        schema="readycall",
    )
    op.create_index(
        "ix_agent_state_log_agent_at",
        "agent_state_log",
        ["agent_id", "at"],
        unique=False,
        schema="readycall",
    )
    op.create_index(
        "ix_agent_state_log_at", "agent_state_log", ["at"], unique=False, schema="readycall"
    )
    op.create_table(
        "call_state_transitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("call_session_id", sa.String(length=40), nullable=False),
        sa.Column("from_state", sa.String(length=24), nullable=True),
        sa.Column("to_state", sa.String(length=24), nullable=False),
        sa.Column("at", readycall.db.base.Utc(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_session_id"],
            ["readycall.call_sessions.call_session_id"],
            name=op.f("fk_call_state_transitions_call_session_id_call_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_state_transitions")),
        schema="readycall",
    )
    op.create_index(
        "ix_call_state_transitions_call",
        "call_state_transitions",
        ["call_session_id", "id"],
        unique=False,
        schema="readycall",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_call_state_transitions_call", table_name="call_state_transitions", schema="readycall"
    )
    op.drop_table("call_state_transitions", schema="readycall")
    op.drop_index("ix_agent_state_log_at", table_name="agent_state_log", schema="readycall")
    op.drop_index("ix_agent_state_log_agent_at", table_name="agent_state_log", schema="readycall")
    op.drop_table("agent_state_log", schema="readycall")
    op.drop_index(
        "ix_call_sessions_telephony_call_id", table_name="call_sessions", schema="readycall"
    )
    op.drop_index("ix_call_sessions_state", table_name="call_sessions", schema="readycall")
    op.drop_index("ix_call_sessions_queued_at", table_name="call_sessions", schema="readycall")
    op.drop_index("ix_call_sessions_customer_id", table_name="call_sessions", schema="readycall")
    op.drop_table("call_sessions", schema="readycall")
    # ### end Alembic commands ###
