"""audio_recordings

Revision ID: 7bb7b6ffe6ba
Revises: 97e97bdfe222
Create Date: 2026-09-06 02:09:03.671741

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types are emitted by autogenerate as fully-qualified names, so the module
# has to be importable from inside the migration. Without this every generated file dies
# with `NameError: name 'readycall' is not defined` on the first Utc or Json column.
import readycall.db.base

# revision identifiers, used by Alembic.
revision: str = "7bb7b6ffe6ba"
down_revision: str | Sequence[str] | None = "97e97bdfe222"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_recordings",
        sa.Column("recording_id", sa.String(length=40), nullable=False),
        sa.Column("call_session_id", sa.String(length=40), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("storage_ref", sa.String(length=512), nullable=False),
        sa.Column("created_at", readycall.db.base.Utc(timezone=True), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("audio_format", sa.String(length=24), nullable=False),
        sa.Column("encryption_key_ref", sa.String(length=128), nullable=True),
        sa.Column("delete_after", readycall.db.base.Utc(timezone=True), nullable=True),
        sa.Column("intake_id", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_session_id"],
            ["readycall.call_sessions.call_session_id"],
            name=op.f("fk_audio_recordings_call_session_id_call_sessions"),
        ),
        sa.PrimaryKeyConstraint("recording_id", name=op.f("pk_audio_recordings")),
        schema="readycall",
    )
    op.create_index(
        "ix_audio_recordings_call",
        "audio_recordings",
        ["call_session_id"],
        unique=False,
        schema="readycall",
    )
    op.create_index(
        "ix_audio_recordings_delete_after",
        "audio_recordings",
        ["delete_after"],
        unique=False,
        schema="readycall",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_audio_recordings_delete_after", table_name="audio_recordings", schema="readycall"
    )
    op.drop_index("ix_audio_recordings_call", table_name="audio_recordings", schema="readycall")
    op.drop_table("audio_recordings", schema="readycall")
    # ### end Alembic commands ###
