"""assignments, attestations, captures, decisions, snapshots, wrapups

Revision ID: 97e97bdfe222
Revises: 6991a6b2b212
Create Date: 2026-08-25 17:13:14.786940

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types are emitted by autogenerate as fully-qualified names, so the module
# has to be importable from inside the migration. Without this every generated file dies
# with `NameError: name 'readycall' is not defined` on the first Utc or Json column.
import readycall.db.base

# revision identifiers, used by Alembic.
revision: str = "97e97bdfe222"
down_revision: str | Sequence[str] | None = "6991a6b2b212"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "context_snapshots",
        sa.Column("snapshot_id", sa.String(length=40), nullable=False),
        sa.Column("customer_id", sa.String(length=32), nullable=True),
        sa.Column("built_at", readycall.db.base.Utc(timezone=True), nullable=False),
        sa.Column("payload", readycall.db.base.Json(), nullable=False),
        sa.Column("provenance", readycall.db.base.Json(), nullable=False),
        sa.Column("provider_name", sa.String(length=32), nullable=False),
        sa.Column("build_ms", sa.Float(), nullable=True),
        sa.Column("degraded", sa.String(length=24), nullable=False),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_context_snapshots")),
        schema="readycall",
    )
    op.create_index(
        "ix_context_snapshots_customer",
        "context_snapshots",
        ["customer_id", "built_at"],
        unique=False,
        schema="readycall",
    )
    op.create_table(
        "assignments",
        sa.Column("assignment_id", sa.String(length=40), nullable=False),
        sa.Column("call_session_id", sa.String(length=40), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("offered_at", readycall.db.base.Utc(timezone=True), nullable=False),
        sa.Column("accept_mode", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("accepted_at", readycall.db.base.Utc(timezone=True), nullable=True),
        sa.Column("decline_reason", sa.String(length=64), nullable=True),
        sa.Column("bridged_at", readycall.db.base.Utc(timezone=True), nullable=True),
        sa.Column("ended_at", readycall.db.base.Utc(timezone=True), nullable=True),
        sa.Column("acw_started_at", readycall.db.base.Utc(timezone=True), nullable=True),
        sa.Column("acw_ended_at", readycall.db.base.Utc(timezone=True), nullable=True),
        sa.Column("acw_ended_by", sa.String(length=24), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_session_id"],
            ["readycall.call_sessions.call_session_id"],
            name=op.f("fk_assignments_call_session_id_call_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("assignment_id", name=op.f("pk_assignments")),
        schema="readycall",
    )
    op.create_index(
        "ix_assignments_agent",
        "assignments",
        ["agent_id", "offered_at"],
        unique=False,
        schema="readycall",
    )
    op.create_index(
        "ix_assignments_call",
        "assignments",
        ["call_session_id", "offered_at"],
        unique=False,
        schema="readycall",
    )
    op.create_table(
        "call_wrapups",
        sa.Column("call_session_id", sa.String(length=40), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("saved_at", readycall.db.base.Utc(timezone=True), nullable=False),
        sa.Column("disposition", sa.String(length=64), nullable=False),
        sa.Column("notes", sa.String(length=4000), nullable=True),
        sa.Column("follow_up_required", sa.Boolean(), nullable=False),
        sa.Column("was_edited", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_session_id"],
            ["readycall.call_sessions.call_session_id"],
            name=op.f("fk_call_wrapups_call_session_id_call_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("call_session_id", name=op.f("pk_call_wrapups")),
        schema="readycall",
    )
    op.create_table(
        "identity_attestations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("call_session_id", sa.String(length=40), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("at", readycall.db.base.Utc(timezone=True), nullable=False),
        sa.Column("challenge", sa.String(length=32), nullable=True),
        sa.Column("challenge_note", sa.String(length=512), nullable=True),
        sa.Column("rejected_customer_id", sa.String(length=32), nullable=True),
        sa.Column("caller_name", sa.String(length=128), nullable=True),
        sa.Column("relationship", sa.String(length=64), nullable=True),
        sa.Column("note", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_session_id"],
            ["readycall.call_sessions.call_session_id"],
            name=op.f("fk_identity_attestations_call_session_id_call_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_attestations")),
        schema="readycall",
    )
    op.create_index(
        "ix_identity_attestations_call_id",
        "identity_attestations",
        ["call_session_id", "id"],
        unique=False,
        schema="readycall",
    )
    op.create_table(
        "keypad_captures",
        sa.Column("capture_id", sa.String(length=40), nullable=False),
        sa.Column("call_session_id", sa.String(length=40), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("started_at", readycall.db.base.Utc(timezone=True), nullable=False),
        sa.Column("stopped_at", readycall.db.base.Utc(timezone=True), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("labelled_as", sa.String(length=32), nullable=True),
        sa.Column("masked", sa.String(length=64), nullable=False),
        sa.Column("digit_count", sa.Integer(), nullable=False),
        sa.Column("digits", sa.String(length=64), nullable=True),
        sa.Column("lookups", readycall.db.base.Json(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_session_id"],
            ["readycall.call_sessions.call_session_id"],
            name=op.f("fk_keypad_captures_call_session_id_call_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("capture_id", name=op.f("pk_keypad_captures")),
        schema="readycall",
    )
    op.create_index(
        "ix_keypad_captures_call",
        "keypad_captures",
        ["call_session_id", "started_at"],
        unique=False,
        schema="readycall",
    )
    op.create_table(
        "matching_decisions",
        sa.Column("decision_id", sa.String(length=40), nullable=False),
        sa.Column("call_session_id", sa.String(length=40), nullable=False),
        sa.Column("at", readycall.db.base.Utc(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("chosen_agent_id", sa.String(length=32), nullable=True),
        sa.Column("total_score", sa.Float(), nullable=True),
        sa.Column("deferred_for_agent_id", sa.String(length=32), nullable=True),
        sa.Column("expected_free_in_s", sa.Float(), nullable=True),
        sa.Column("fit_gap", sa.Float(), nullable=True),
        sa.Column("rationale_th", sa.String(length=512), nullable=True),
        sa.Column("rationale_en", sa.String(length=512), nullable=True),
        sa.Column("weights_version", sa.String(length=32), nullable=False),
        sa.Column("solver", sa.String(length=16), nullable=False),
        sa.Column("decide_ms", sa.Float(), nullable=True),
        sa.Column("candidates", readycall.db.base.Json(), nullable=False),
        sa.Column("urgency", readycall.db.base.Json(), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_session_id"],
            ["readycall.call_sessions.call_session_id"],
            name=op.f("fk_matching_decisions_call_session_id_call_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_matching_decisions")),
        schema="readycall",
    )
    op.create_index(
        "ix_matching_decisions_call_at",
        "matching_decisions",
        ["call_session_id", "at"],
        unique=False,
        schema="readycall",
    )
    op.create_index(
        "ix_matching_decisions_kind_at",
        "matching_decisions",
        ["kind", "at"],
        unique=False,
        schema="readycall",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_matching_decisions_kind_at", table_name="matching_decisions", schema="readycall"
    )
    op.drop_index(
        "ix_matching_decisions_call_at", table_name="matching_decisions", schema="readycall"
    )
    op.drop_table("matching_decisions", schema="readycall")
    op.drop_index("ix_keypad_captures_call", table_name="keypad_captures", schema="readycall")
    op.drop_table("keypad_captures", schema="readycall")
    op.drop_index(
        "ix_identity_attestations_call_id", table_name="identity_attestations", schema="readycall"
    )
    op.drop_table("identity_attestations", schema="readycall")
    op.drop_table("call_wrapups", schema="readycall")
    op.drop_index("ix_assignments_call", table_name="assignments", schema="readycall")
    op.drop_index("ix_assignments_agent", table_name="assignments", schema="readycall")
    op.drop_table("assignments", schema="readycall")
    op.drop_index(
        "ix_context_snapshots_customer", table_name="context_snapshots", schema="readycall"
    )
    op.drop_table("context_snapshots", schema="readycall")
    # ### end Alembic commands ###
